<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Drug;

class DrugSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $drugs = [
            // Existing drugs
            [
                'name' => 'Paracetamol',
                'generic_name' => 'Acetaminophen',
                'description' => 'Pain reliever and fever reducer',
                'dosage_form' => 'tablet',
                'strength' => '500mg',
                'indications' => 'Pain relief, fever reduction',
                'contraindications' => 'Liver disease, alcohol abuse',
                'side_effects' => 'Nausea, rash, liver damage (rare)',
                'storage_instructions' => 'Store at room temperature, away from moisture',
                'is_active' => true,
            ],
            [
                'name' => 'Aspirin',
                'generic_name' => 'Acetylsalicylic acid',
                'description' => 'Anti-inflammatory and pain reliever',
                'dosage_form' => 'tablet',
                'strength' => '325mg',
                'indications' => 'Pain relief, anti-inflammatory, blood thinner',
                'contraindications' => 'Bleeding disorders, stomach ulcers, children under 12',
                'side_effects' => 'Stomach irritation, bleeding risk',
                'storage_instructions' => 'Store in cool, dry place',
                'is_active' => true,
            ],
            [
                'name' => 'Ibuprofen',
                'generic_name' => 'Ibuprofen',
                'description' => 'Non-steroidal anti-inflammatory drug (NSAID)',
                'dosage_form' => 'tablet',
                'strength' => '400mg',
                'indications' => 'Pain relief, inflammation reduction, fever',
                'contraindications' => 'Stomach ulcers, heart disease, kidney problems',
                'side_effects' => 'Stomach upset, dizziness, headache',
                'storage_instructions' => 'Store at room temperature',
                'is_active' => true,
            ],
            [
                'name' => 'Metformin',
                'generic_name' => 'Metformin hydrochloride',
                'description' => 'Antidiabetic medication',
                'dosage_form' => 'tablet',
                'strength' => '500mg',
                'indications' => 'Type 2 diabetes management',
                'contraindications' => 'Kidney disease, liver disease, heart failure',
                'side_effects' => 'Nausea, diarrhea, metallic taste',
                'storage_instructions' => 'Store at room temperature, protect from moisture',
                'is_active' => true,
            ],
            [
                'name' => 'Lisinopril',
                'generic_name' => 'Lisinopril',
                'description' => 'ACE inhibitor for blood pressure control',
                'dosage_form' => 'tablet',
                'strength' => '10mg',
                'indications' => 'High blood pressure, heart failure',
                'contraindications' => 'Pregnancy, kidney artery stenosis',
                'side_effects' => 'Dry cough, dizziness, fatigue',
                'storage_instructions' => 'Store at room temperature',
                'is_active' => true,
            ],
            [
                'name' => 'Atorvastatin',
                'generic_name' => 'Atorvastatin calcium',
                'description' => 'Statin for cholesterol management',
                'dosage_form' => 'tablet',
                'strength' => '20mg',
                'indications' => 'High cholesterol, cardiovascular protection',
                'contraindications' => 'Liver disease, pregnancy',
                'side_effects' => 'Muscle pain, liver enzyme elevation',
                'storage_instructions' => 'Store at room temperature',
                'is_active' => true,
            ],
            // Additional drugs to match medication templates
            [
                'name' => 'Insulin Glargine',
                'generic_name' => 'Insulin glargine',
                'description' => 'Long-acting insulin for diabetes management',
                'dosage_form' => 'injection',
                'strength' => '100 units/mL',
                'indications' => 'Type 1 and Type 2 diabetes',
                'contraindications' => 'Hypoglycemia, allergy to insulin',
                'side_effects' => 'Hypoglycemia, injection site reactions',
                'storage_instructions' => 'Refrigerate, protect from light',
                'is_active' => true,
            ],
            [
                'name' => 'Donepezil',
                'generic_name' => 'Donepezil hydrochloride',
                'description' => 'Cholinesterase inhibitor for Alzheimer\'s disease',
                'dosage_form' => 'tablet',
                'strength' => '5mg',
                'indications' => 'Alzheimer\'s disease, dementia',
                'contraindications' => 'Severe liver disease, allergy to donepezil',
                'side_effects' => 'Nausea, diarrhea, insomnia',
                'storage_instructions' => 'Store at room temperature',
                'is_active' => true,
            ],
            [
                'name' => 'Memantine',
                'generic_name' => 'Memantine hydrochloride',
                'description' => 'NMDA receptor antagonist for dementia',
                'dosage_form' => 'tablet',
                'strength' => '10mg',
                'indications' => 'Moderate to severe Alzheimer\'s disease',
                'contraindications' => 'Severe kidney disease, allergy to memantine',
                'side_effects' => 'Dizziness, headache, constipation',
                'storage_instructions' => 'Store at room temperature',
                'is_active' => true,
            ],
            [
                'name' => 'Acetaminophen',
                'generic_name' => 'Acetaminophen',
                'description' => 'Pain reliever and fever reducer',
                'dosage_form' => 'tablet',
                'strength' => '500mg',
                'indications' => 'Pain relief, fever reduction',
                'contraindications' => 'Liver disease, alcohol abuse',
                'side_effects' => 'Nausea, rash, liver damage (rare)',
                'storage_instructions' => 'Store at room temperature',
                'is_active' => true,
            ],
            [
                'name' => 'Calcium Carbonate',
                'generic_name' => 'Calcium carbonate',
                'description' => 'Calcium supplement for bone health',
                'dosage_form' => 'tablet',
                'strength' => '600mg',
                'indications' => 'Osteoporosis, calcium deficiency',
                'contraindications' => 'Hypercalcemia, kidney stones',
                'side_effects' => 'Constipation, gas, bloating',
                'storage_instructions' => 'Store at room temperature',
                'is_active' => true,
            ],
            [
                'name' => 'Vitamin D3',
                'generic_name' => 'Cholecalciferol',
                'description' => 'Vitamin D supplement for bone health',
                'dosage_form' => 'tablet',
                'strength' => '1000 IU',
                'indications' => 'Vitamin D deficiency, bone health',
                'contraindications' => 'Hypercalcemia, kidney disease',
                'side_effects' => 'Nausea, weakness, kidney stones (rare)',
                'storage_instructions' => 'Store at room temperature',
                'is_active' => true,
            ],
            [
                'name' => 'Carbidopa-Levodopa',
                'generic_name' => 'Carbidopa/Levodopa',
                'description' => 'Combination medication for Parkinson\'s disease',
                'dosage_form' => 'tablet',
                'strength' => '25mg/100mg',
                'indications' => 'Parkinson\'s disease, parkinsonism',
                'contraindications' => 'Narrow-angle glaucoma, melanoma',
                'side_effects' => 'Nausea, dizziness, dyskinesia',
                'storage_instructions' => 'Store at room temperature',
                'is_active' => true,
            ],
            [
                'name' => 'Pramipexole',
                'generic_name' => 'Pramipexole dihydrochloride',
                'description' => 'Dopamine agonist for Parkinson\'s disease',
                'dosage_form' => 'tablet',
                'strength' => '0.25mg',
                'indications' => 'Parkinson\'s disease, restless legs syndrome',
                'contraindications' => 'Severe kidney disease, allergy to pramipexole',
                'side_effects' => 'Drowsiness, dizziness, nausea',
                'storage_instructions' => 'Store at room temperature',
                'is_active' => true,
            ],
            [
                'name' => 'Albuterol Inhaler',
                'generic_name' => 'Albuterol sulfate',
                'description' => 'Bronchodilator for respiratory conditions',
                'dosage_form' => 'inhaler',
                'strength' => '90 mcg/actuation',
                'indications' => 'COPD, asthma, bronchospasm',
                'contraindications' => 'Allergy to albuterol, severe heart disease',
                'side_effects' => 'Tremor, nervousness, headache',
                'storage_instructions' => 'Store at room temperature',
                'is_active' => true,
            ],
            [
                'name' => 'Tiotropium',
                'generic_name' => 'Tiotropium bromide',
                'description' => 'Long-acting bronchodilator for COPD',
                'dosage_form' => 'inhaler',
                'strength' => '18 mcg/capsule',
                'indications' => 'COPD maintenance therapy',
                'contraindications' => 'Allergy to tiotropium, severe kidney disease',
                'side_effects' => 'Dry mouth, constipation, blurred vision',
                'storage_instructions' => 'Store at room temperature',
                'is_active' => true,
            ],
            [
                'name' => 'Latanoprost Eye Drops',
                'generic_name' => 'Latanoprost',
                'description' => 'Prostaglandin analog for glaucoma',
                'dosage_form' => 'eye drops',
                'strength' => '0.005%',
                'indications' => 'Glaucoma, ocular hypertension',
                'contraindications' => 'Allergy to latanoprost, active eye infection',
                'side_effects' => 'Eye irritation, darkening of iris',
                'storage_instructions' => 'Refrigerate after opening',
                'is_active' => true,
            ],
            [
                'name' => 'Multivitamin',
                'generic_name' => 'Multivitamin',
                'description' => 'Daily vitamin and mineral supplement',
                'dosage_form' => 'tablet',
                'strength' => 'Various',
                'indications' => 'General health, vitamin deficiency',
                'contraindications' => 'Hypervitaminosis, allergy to components',
                'side_effects' => 'Nausea, constipation, discolored urine',
                'storage_instructions' => 'Store at room temperature',
                'is_active' => true,
            ],
            [
                'name' => 'Loratadine',
                'generic_name' => 'Loratadine',
                'description' => 'Antihistamine for allergy relief',
                'dosage_form' => 'tablet',
                'strength' => '10mg',
                'indications' => 'Allergic rhinitis, urticaria',
                'contraindications' => 'Allergy to loratadine, severe liver disease',
                'side_effects' => 'Drowsiness, dry mouth, headache',
                'storage_instructions' => 'Store at room temperature',
                'is_active' => true,
            ],
        ];

        foreach ($drugs as $drug) {
            Drug::create($drug);
        }
    }
}
